### ISSUE TITLE
Introduce const

### ISSUE THREAD

**Issue by IanaKhitsko** [ihor-melnyk1/the-game#1]
https://github.com/ihor-melnyk1/the-game/blob/f5908a676200d66294fd892e5b62b65f853fd841/checkWins.js#L21

I would add const for 5

**Comment by ihor-melnyk1** [comment]
Created variable matchesToWin
https://github.com/ihor-melnyk1/the-game/blob/66e0750ecd5d14321e16e0e135d2dfd914bfd495/checkWins.js#L1
