### ISSUE TITLE
Move similar code to separate method

### ISSUE THREAD

**Issue by IanaKhitsko** [ihor-melnyk1/the-game#2]
https://github.com/ihor-melnyk1/the-game/blob/f5908a676200d66294fd892e5b62b65f853fd841/checkWins.js#L76-L92

this looks similar to bottom block. Can you combine it somehow to a separate method?

**Comment by ihor-melnyk1** [comment]
Created new function to check diagonal win to reduce similar code
https://github.com/ihor-melnyk1/the-game/blob/66e0750ecd5d14321e16e0e135d2dfd914bfd495/checkWins.js#L69
