### ISSUE TITLE
Introduce const for 19

### ISSUE THREAD

**Issue by IanaKhitsko** [ihor-melnyk1/the-game#3]
https://github.com/ihor-melnyk1/the-game/blob/f5908a676200d66294fd892e5b62b65f853fd841/parseInput.js#L10

Introduce const for 19 and use it everywhere

**Comment by ihor-melnyk1** [comment]
Added new variable gameLength
https://github.com/ihor-melnyk1/the-game/blob/66e0750ecd5d14321e16e0e135d2dfd914bfd495/parseInput.js#L9
