### ISSUE TITLE
Remove duplicate code

### ISSUE THREAD

**Issue by sverh99** [ihor-melnyk1/the-game#4]
https://github.com/ihor-melnyk1/the-game/blob/66e0750ecd5d14321e16e0e135d2dfd914bfd495/checkWins.js#L25C4-L29C8

Refactor to remove duplicate code (line 25 & 28)

**Comment by ihor-melnyk1** [comment]
https://github.com/ihor-melnyk1/the-game/blob/709ce826bc2a23065e965dd63b79dfea8b1f5d78/checkWins.js#L24
Moved to variable to remove duplicate code
