### ISSUE TITLE
Move 4 to const

### ISSUE THREAD

**Issue by sverh99** [ihor-melnyk1/the-game#5]
https://github.com/ihor-melnyk1/the-game/blob/66e0750ecd5d14321e16e0e135d2dfd914bfd495/checkWins.js#L84

Move 4 to a const variable

**Comment by ihor-melnyk1** [comment]
https://github.com/ihor-melnyk1/the-game/blob/709ce826bc2a23065e965dd63b79dfea8b1f5d78/checkWins.js#L2
Moved to a variable
